apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: my-app-lb
spec:
  type: LoadBalancer
  selector:
    app: my-app # this is the same as label "app" in Pod config so that Service nows which resource to attach to
  ports:
    - name: http
      port: 80
      targetPort: 80