apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      name: my-app-pod
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: stacksimplify/kubenginx:2.0.0
          ports:
            - containerPort: 80