apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  labels:
    app: my-app-be
    tier: backend
spec:
  type: ClusterIP # could skip providing this, as this is default
  selector:
    app: my-app-be
  ports:
    - port: 8080
      targetPort: 8080