apiVersion: v1
kind: Service
metadata:
  name: front-lb
  labels:
    app: my-app-frontend
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: my-app-frontend
  ports:
    - port: 80
      targetPort: 80