apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image:  mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: dbpassword11
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql # Where will the data be stored within the database
              name: my-sql-persistent-storage
            - name: usermanagement-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d # Has to be exactly like that
      volumes:
        - name: my-sql-persistent-storage
          persistentVolumeClaim:
            claimName: my-pvc
        - name: usermanagement-dbcreation-script
          configMap:
            name: usermanagement-dbcreation-script