apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo # balanced disk in GKE
  resources:
    requests:
      storage: 4Gi # 4 GB
